@startuml
hide footbox
actor User
participant "LogicManager" as L
participant "AddressBookParser" as ABP
participant "RemarkCommandParser" as RCP
participant "RemarkCommand" as RC
participant "Model" as M

User -> L : execute("remark 1 rm/Likes dogs")
activate L

L -> ABP : parseCommand("remark 1 rm/Likes dogs")
activate ABP

ABP -> RCP : parse(" 1 rm/Likes dogs")
activate RCP
RCP -> RC : RemarkCommand(1, "Likes dogs")
activate RC
RC --> RCP : remark command
deactivate RC
RCP --> ABP : remark command
deactivate RCP
ABP --> L : remark command
deactivate ABP

L -> RC : execute(Model)
activate RC
RC -> M : getFilteredPersonList()
activate M
M --> RC : List<Person>
RC -> RC : create editedPerson with new remark
RC -> M : setPerson(personToEdit, editedPerson)
RC -> M : updateFilteredPersonList(PREDICATE_SHOW_ALL_PERSONS)
RC -> M : CommandResult("Added remark to Person: ...")
M --> RC : command result
deactivate M
RC --> L : command result
deactivate RC
L --> User : command result
deactivate L
@enduml
