@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam classFontSize 13
skinparam packageStyle rectangle

class RemarkCommand {
    --
    + execute(model: Model) : CommandResult
    - generateSuccessMessage(personToEdit: Person) : String
}

class "{abstract}\nCommand" as Command {
    + {abstract} execute(model: Model) : CommandResult
}

class Index

class "<<interface>>\nModel" as Model {
}

class Person

class Remark {
    + value
}

' Relationships with multiplicities
RemarkCommand --|> Command
RemarkCommand --> "1" Index : index
RemarkCommand --> "1" Remark : remark
RemarkCommand ..> Model : uses >
Command ...> Model : uses >
Model --> "1..*" Person : manages >
Person *-- "1" Remark : remark
@enduml
