@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

if ("Command modifies Address Book?") then ([Yes])
    :Purge redo states;
    :Save current Address Book to history\n(addressBookStateList);
else ([No])
    :No data change — nothing to commit;
endif
stop
@enduml

